### ISSUE TITLE
Add an option to remove song from trashcan. Add a confirmation form when the delete option is used. 

### ISSUE THREAD

**Issue by HarryHeights** [Crypto-Android-Apps/ACG-Player#65]
Sorry, but this in an indirect feature request and a question. I wanted to inquire;

What happens when I delete a song from the trashcan?
Does it get permanently deleted or removed from the trashcan?

I'm asking because I was indirectly testing the feature today and I added some songs to the trashcan. I deleted the songs hoping to find them back on my song list but I didn't. This led me to think that I might have permanently deleted the song.  If that's the case, then it isn't good at all. 
Now for my feature request;

If using the delete option deletes the song from my storage directly, then there should be another option in the options menu. The option should be 'remove from 'trashcan'.  Or you could still maintain only the delete button. But when it is clicked, there should be an option to delete the song permanently, or deleted from the trashcan. 
For my next request; if you decide to go with my former suggest (ie adding a remove button), then I'm requesting that a 'confirmation request form' should be added when I use the delete option. It was weird that as soon as I clicked delete, the song just vanished. 

Tell me what you think. Thanks.

**Comment by AugustToko** [comment]
First of all, I am very sorry, because of my ambiguous design, caused the user to misuse.
I will make the following reforms (menu button):
Add "Empty Trash (on the title bar)": This will permanently delete your songs in the Trash.
Add "Restore (can single or multi-select songs on the title bar)": This will restore all songs from the trash (not permanently deleted).

For now, if you do the following on the song you want to trash, the song will be permanently deleted: "Click the three-dot button and then delete it."

**Comment by AugustToko** [comment]
Upgrade to [ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases)
